// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf6FXbN7_hzzvIjqbaiKdsgtbkBETULO8',
    appId: '1:195699645499:web:220ea541333d989bab501e',
    messagingSenderId: '195699645499',
    projectId: 'quicksos-4575c',
    authDomain: 'quicksos-4575c.firebaseapp.com',
    storageBucket: 'quicksos-4575c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3EA48AqRPi5UrVFjfKZOOTQQBKSNUAR8',
    appId: '1:195699645499:android:b9d3b3589d4639edab501e',
    messagingSenderId: '195699645499',
    projectId: 'quicksos-4575c',
    storageBucket: 'quicksos-4575c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSyxSUQzhAVNDskp5Kw688kHpkjw-bs_s',
    appId: '1:195699645499:ios:6e253f8ace5b2ea9ab501e',
    messagingSenderId: '195699645499',
    projectId: 'quicksos-4575c',
    storageBucket: 'quicksos-4575c.firebasestorage.app',
    iosBundleId: 'com.example.quicksosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSyxSUQzhAVNDskp5Kw688kHpkjw-bs_s',
    appId: '1:195699645499:ios:6e253f8ace5b2ea9ab501e',
    messagingSenderId: '195699645499',
    projectId: 'quicksos-4575c',
    storageBucket: 'quicksos-4575c.firebasestorage.app',
    iosBundleId: 'com.example.quicksosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf6FXbN7_hzzvIjqbaiKdsgtbkBETULO8',
    appId: '1:195699645499:web:b3680b14d20c627bab501e',
    messagingSenderId: '195699645499',
    projectId: 'quicksos-4575c',
    authDomain: 'quicksos-4575c.firebaseapp.com',
    storageBucket: 'quicksos-4575c.firebasestorage.app',
  );

}